name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
          flutter-version: 3.19.6

      - name: Get Flutter packages
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

      - name: Run Flutter unit tests
        run: flutter test
